### ISSUE TITLE
Several warnings on import of the FizzySteamyMirror v1.2.0 package

### ISSUE THREAD

**Issue by Jakob-PB** [Raystorms/FizzySteamyMirror#13]
This transport immediately throws several warnings when imported into Unity 2019.2.1f1. The warnings are:

> The event 'Server.OnReceivedError' is never used
warning CS0067: Assets\Mirror\Runtime\Transport\FizzySteamyMirror\Server.cs(85,45)

and

> Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
warning CS4014: Assets\Mirror\Runtime\Transport\FizzySteamyMirror\Server.cs(116,13)

The rest of the warnings can be fixed with [this pull request](https://github.com/rlabrecque/Steamworks.NET/pull/294) and are related to Steamworks.NET.

**Comment by LukeSeers** [comment]
I'm sorry for the slow reply. This ticket was created on **Aug 22, 2019**  before I spend time looking into this, I would appreciate to know if this issues has been resolved?

**Comment by LukeSeers** [comment]
If your still having these issues please reopen this ticket. Thank you.
